#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     lf,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     lr,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rf,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     rr,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     E,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "BaseClass.c"

task main()
{
	waitForStart();
	while(true)
	{
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y1) < 75 && abs(joystick.joy1_y2) > 75)
		{
			if(joystick.joy1_y1 < 75)
			{
				straightNoWait(100);
			}
			else if(joystick.joy1_y1 > -75)
			{
				straightNoWait(-100);
			}
			else
			{
				straightNoWait(joystick.joy1_y1);
			}
		}
		else if(joystick.joy1_y2 < 75)
		{
			if(joystick.joy1_y2 > 75)
			{
				turnNoWait(100, 1);
			}
			else if(joystick.joy1_y2 > -75)
			{
					turnNoWait(-100, 1);
			}
			else if(joystick.joy1_y2 == 0)
			{
				motor[rf] = 0;
				motor[rr] = 0;
			}
			else
			{
				turnNoWait(joystick.joy1_y2, 1);
			}
		}
		else if(joystick.joy1_y1 < 75)
		{
			if(joystick.joy1_y1 > 100)
			{
				turnNoWait(100, 0);
			}
			else if(joystick.joy1_y1 < -100)
			{
					turnNoWait(-100, 0);
			}
			else if(joystick.joy1_y1 == 0)
			{
				motor[lf] = 0;
				motor[lr] = 0;
			}
			else
			{
				turnNoWait(joystick.joy1_y1, 0);
			}
		}
		else
		{
			motor[lf] = 0;
			motor[lr] = 0;
			motor[rf] = 0;
			motor[rr] = 0;
		}
		if(joystick.joy2_y1 < 75)
		{
				if(joystick.joy2_y1 > 100)
			{
				armNoWait(100);
			}
			else if(joystick.joy1_y1 < -100)
			{
					armNoWait(-100);
			}
			else
			{
				armNoWait(joystick.joy2_y1);
			}
		}
		else
		{
			motor[E] = 0;
		}
		if(joy1Btn(7) == 1)
		{
			hand();
		}
		else
		{
			stopHand();
		}
		if(joy1Btn(8) == 1)
		{
			handBack();
		}
		else
		{
			stopHand();
		}

	}
}
